# generated-from:e09dee96ebf4666ccbcec622d28d1772a2c1f53310b3395b4114a1fce494a91f DO NOT REMOVE, DO UPDATE

ACHTestHarness:
  Servers:
    FTP:
      RootPath: "./storage/ftp/"
      Hostname: "localhost"
      Port: 2222
    Admin:
      Bind:
        Address: ":3333"
  Responses: []
