# generated-from:87a285b9700150cb5dadffcf3b5525224fba53639666434b20bee326dcd94fc5 DO NOT REMOVE, DO UPDATE

name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Install
      run: make install

    - name: Check
      run: make check
      env:
        GOLANGCI_LINTERS: gosec

    - name: Upload Code Coverage
      if: runner.os == 'Linux'
      run: bash <(curl -s https://codecov.io/bash)

    - name: Docker Build
      if: runner.os == 'Linux'
      run: make dev-docker

    - name: Docker Push
      if: runner.os == 'Linux' && github.repository == 'moov-io'
      run: |+
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          make dev-push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
